#!/usr/bin/python

import os
import requests
import pydicom
from pathlib import Path
from urllib3.filepost import encode_multipart_formdata, choose_boundary

dicom_server_name = "{dicom-name}"
path_to_dicoms_dir = "{path}"

base_url = "{base_url}}"



def encode_multipart_related(fields, boundary=None):
    if boundary is None:
        boundary = choose_boundary()

    body, _ = encode_multipart_formdata(fields, boundary)
    content_type = str('multipart/related; boundary=%s' % boundary)

    return body, content_type


client = requests.session()
dirEntries = os.listdir(path_to_dicoms_dir)
for dir in dirEntries:
    fileEntries = os.listdir(Path(path_to_dicoms_dir).joinpath(dir))
    files = {}
    for file in fileEntries:
        filepath = Path(path_to_dicoms_dir).joinpath(dir).joinpath(file)
        print("Working on "+filepath.name)
        with open(filepath, 'rb') as reader:
            rawfile = reader.read()            
            files[filepath.name] = ('dicomfile', rawfile, 'application/dicom')
    
    #encode as multipart_related
    body, content_type = encode_multipart_related(fields = files)

    headers = {'Accept':'application/dicom+json', "Content-Type":content_type}

    url = f'{base_url}/studies'
    response = client.post(url, body, headers=headers, verify=False)

    print('response:', response)


